FROM rust:latest

ENV TZ=Asia/Novosibirsk

RUN apt-get update -y

RUN git clone --depth 1 --branch v0.7.3 https://github.com/skytable/skytable.git

RUN cd skytable && cargo build --release

EXPOSE 2003

CMD cd skytable && cargo run --release --bin skyd