FROM rust:latest

ENV TZ=Asia/Novosibirsk

RUN apt-get update -y

RUN git clone https://github.com/stepanov-denis/ats-monitoring

RUN cd ats-monitoring && cargo build --release

EXPOSE 5432

EXPOSE 2003

CMD cd ats-monitoring && RUST_LOG=debug cargo run --release