FROM rust:latest

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Asia/Novosibirsk

RUN apt-get update -y

RUN git clone --depth 1 --branch v0.7.3 https://github.com/skytable/skytable.git

RUN cd skytable && cargo build --release

RUN cargo install ats-monitoring

EXPOSE 5432

CMD cd skytable && cargo run --bin skydb && ats-monitoring