FROM postgres:13.6

# ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Asia/Novosibirsk

RUN apt-get update -y

EXPOSE 5432

CMD bash

# CMD service postgresql start && su postgres bash -c "psql -c \"CREATE USER stepanov WITH CREATEDB PASSWORD 'postgres';\"" && bash